name: Add labels to issue and PR
on:
  issues: 
    types:
      - opened
  pull_request: 
    types:
      - opened

jobs:
  teams:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: do3-2021/kudo-team-parser-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
